Lecture 2/hw
itsanti/react-20230914 pull request #2
Opened 2023-09-25 23:10 UTC by itsanti

добавил стили чисто символически, чтобы активная кнопка хоть как-то выделялась.

2023-09-28 14:45 UTC, SArchieEdu requested changes

2023-09-28 14:45 UTC, SArchieEdu commented on src/components/Tabs/component.jsx
> +export const Tabs = ({data}) => {
Лучше чтобы табы отвечали только за табы. Покажу на лекции как сделать иначе.

2023-09-28 14:45 UTC, SArchieEdu commented on src/components/Tabs/component.jsx
> +                data.map(({id, name}) => <React.Fragment key={id}>
Фрагмент тут лишний, можно просто Button использовать

2023-09-28 14:45 UTC, SArchieEdu commented on src/components/Tabs/component.jsx
> +                data.filter(({id}) => id === activeRestaurantId).map((item) => (
а если несколько ресторанов будет? лучше использовать find в теле компонента, а рисовать уже найденный ресторан

2023-09-28 20:50 UTC, itsanti commented on src/components/Tabs/component.jsx
> +export const Tabs = ({data}) => {
Добавил RestaurantTabs компонент.

2023-09-28 20:54 UTC, itsanti commented on src/components/Tabs/component.jsx
> +                data.map(({id, name}) => <React.Fragment key={id}>
Там стоял фрагмент, т.к. я после кнопки рисовал неразрывный пробел {'\u00A0'}. Убрал, отступ будет в стилях.

2023-10-02 09:03 UTC, SArchieEdu approved these changes
Замечания минимальные. После правки можно сразу мерджить.

2023-10-02 09:03 UTC, SArchieEdu commented on src/pages/Main/component.jsx
> +                data={restaurants}
название data лучше заменить, тк оно слишком общее, restaurants подойдёт лучше

2023-10-02 09:03 UTC, SArchieEdu commented on src/components/MenuItem/component.jsx
> +export const MenuItem = ({name, range}) => {
Лучше переименовать, тк MenuItem жестко привязывает этот компонент к родителю. Лучше Dish

2023-10-02 19:53 UTC, itsanti commented on src/components/MenuItem/component.jsx
> +export const MenuItem = ({name, range}) => {
Переименую в 3 ДЗ

2023-10-02 19:53 UTC, merged